config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }
  
  resources :products do
    resources :comments
  end

  resources :users
  
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  post 'static_pages/thank_you'

  post 'payments/create'
  

  root 'static_pages#landing_page'

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders
  has_many :comments

  validates :name, presence: true

	def average_rating
  	comments.average(:rating).to_f
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  respond_to :json, :html

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      if Rails.env.development?
        @products = Product.where("name LIKE ?", "%#{search_term}%")
      else
        @products = Product.where("name ilike ?", "%#{search_term}%")
      end
    else
      @products = Product.all
    end
    respond_with @products
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(page: params[:page], :per_page => 3)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to :back, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
        <div class="row">
          <hr>
          <p>
          	<%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
            <% if signed_in? && current_user.admin? %>
    						<%= link_to ('<span class="glyphicon glyphicon-remove remove-icon"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
    				<% end %>
    			</p>
          <div class="rated" data-score="<%= comment.rating %>"></div>
          <p><%= comment.body %></p>
        </div>
    <% end %>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control multiline" %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour, class: "form-control" %>
  </div>
  <div class="price">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Save Changes", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4 class="reviews-top">Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>

    <p>
      <%= f.label :body, "Comments" %>
    </p>

    <p>
      <%= f.text_area :body, class: "form-control multiline", placeholder: "Enter your comment here." %>
    </p>

    <p>
      <div class="rating"></div>
    </p>

    <p>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </p>

  <% end %>
<% end %>

app/views/products/_product.html.erb
<% cache product do %>
	<div class="col-sm-6 col-md-4 product-box">
  	<%= image_tag(product.image_url, class: "img-responsive product-image") %>
  	<h1><%= product.name %></h1>
  	<p><%= product.description %></p>
  	<p><%= product.colour %></p>
  	<p><strong>$ <%= product.price %></strong></p>
  	<p class="options"><%= link_to 'Show', product %>
  	<%= link_to 'Edit', edit_product_path(product) %>
  	<%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></p>
	</div><!-- /col -->
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1 >Listing Products</h1>

<div class="container-fluid">
  <div class="row">
    <% cache(cache_key_for_products) do %>
  		<%= render @products %>
		<% end %>
  </div>
</div>

<br>

<p class="options new_prod"><%= link_to 'New Product', new_product_path %></p>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-8 col-md-8">

    <%= image_tag(@product.image_url, data_zoom_image: @product.image_url, class: "product-image img-responsive img-zoom") %>

    </div>

    <% logger.debug "Product: #{@product.name}"%>

    <div class="col-sm-4 col-md-4 data">

      <p>
        <strong><span class="glyphicon glyphicon-gift"></span>&nbsp;Name:</strong>
        <%= @product.name %>
      </p>

      <p>
        <strong><span class="glyphicon glyphicon-pencil"></span>&nbsp;Description:</strong>
        <%= @product.description %>
      </p>

      <p>
        <strong><span class="glyphicon glyphicon-picture"></span>&nbsp;Image url:</strong>
        <%= @product.image_url %>
      </p>

      <p>
        <strong><span class="glyphicon glyphicon-tint"></span>&nbsp;Colour:</strong>
        <%= @product.colour %>
      </p>

      <p>
        <strong><span class="glyphicon glyphicon-euro"></span>&nbsp;Price: </strong>€
        <%= @product.price %>
      </p>

      <h3>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div> </h3>
      
      <%= form_tag "/payments/create" do %>
        <%= render partial: "shared/stripe_checkout_button" %>
      <% end %>

      <%= render 'new_comment' %>
      <%= render 'comments' %>

      <div class="digg_pagination">
        <div class="page_info">
        <%= page_entries_info @comments %>    
        </div>
        <%= will_paginate @comments,:container => false %>
      </div>

    </div>
  </div>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
</div>