config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }
  
  resources :products do
    resources :comments
  end

  resources :users
  
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  post 'static_pages/thank_you'

  post 'payments/create'
  

  root 'static_pages#landing_page'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nameofapp</title>
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>

<body>
<div class="page-wrap"> <!-- needed for sticky footer -->
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
    		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      		<span class="sr-only">Toggle navigation</span>
      		<span class="icon-bar"></span>
      		<span class="icon-bar"></span>
      		<span class="icon-bar"></span>
      		<span class="icon-bar"></span>
      		<span class="icon-bar"></span>
    		</button>
    		<div class="navbar-brand">
    			<%= link_to "Fictional Bike Shop", root_path %>
      		<!-- <a href="#">Fictional Bike Shop</a> -->
    		</div>
  		</div>
  		<div class="navbar-collapse collapse">
    		<ul class="nav navbar-nav">
     			<!-- <li><a href="/static_pages/index.html"><span class="glyphicon glyphicon-home"></span> Home</a></li> -->
     			<li>
      			<%= link_to static_pages_index_path do %>
            	<span class="glyphicon glyphicon-home"></span>&nbsp;Home
            <% end %>
          </li>
     			<!-- <li><a href="/products"><span class="glyphicon glyphicon-gift"></span> Products</a></li> -->
     			<li>
      			<%= link_to products_path do %>
            	<span class="glyphicon glyphicon-gift"></span>&nbsp;Products
            <% end %>
          </li>
     			<!-- <li><a href="/orders"><span class="glyphicon glyphicon-shopping-cart"></span> Orders</a></li> -->
     			<li>
      			<%= link_to orders_path do %>
            	<span class="glyphicon glyphicon-shopping-cart"></span>&nbsp;Orders
            <% end %>
          </li>
      		<!-- <li><a href="/static_pages/about/"><span class="glyphicon glyphicon-info-sign"></span> About</a></li> -->
      		<li>
      			<%= link_to static_pages_about_path do %>
            	<span class="glyphicon glyphicon-info-sign"></span>&nbsp;About
            <% end %>
          </li>
      		<!-- <li><a href="/static_pages/contact/"><span class="glyphicon glyphicon-envelope"></span> Contact</a></li> -->
      		<li>
      			<%= link_to static_pages_contact_path do %>
            	<span class="glyphicon glyphicon-envelope"></span>&nbsp;Contact
            <% end %>
          </li>                  
    		</ul>
    		<ul class="nav pull-right">
  				<li>
  					<% if user_signed_in? %>
    					<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  					<% else %>
    					<%= link_to('Login', new_user_session_path) %>
  					<% end %>
  				</li>
				</ul>
    		<div class="navbar-form navbar-right">
          <%= form_tag("/products", method: "get") do %>
  					<%= label_tag(:q, "Search for:") %>
  					<%= text_field_tag(:q) %>
  					<%= submit_tag("Search") %>
					<% end %>
				</div>
  		</div>
  	</div>
  </nav>

	<p class="firstline">
	</p>

	<% if notice %>
		<p id="notice" class="alert alert-info"><%= notice %></p>
	<% end %>

<% if alert %>
		<p id="alert" class="alert alert-danger"><%= alert %></p>
	<% end %>

	<%= yield %>

</div> <!-- end of .page-wrap needed for sticky footer -->

<footer class="site-footer">
 	&copy; 2016 Jörg Brämer
</footer>

</body>
</html>